# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = 'schulze-vote'
  s.version = '2.0.2'

  s.required_rubygems_version = Gem::Requirement.new('>= 0') if s.respond_to? :required_rubygems_version=
  s.authors = ['Alessandro Rodi']
  s.date = '2015-12-10'
  s.description = 'This gem is a Ruby implementation of the Schulze voting method (with help of the Floyd-Warshall algorithm), a type of the Condorcet voting methods.'
  s.email = 'coorasse@gmail.com'
  s.extra_rdoc_files = [
    'LICENSE',
    'README.md'
  ]

  s.homepage = 'http://github.com/coorasse/schulze-vote'
  s.licenses = ['MIT']
  s.require_paths = ['lib']
  s.rubygems_version = '1.6.2'
  s.summary = 'Schulze method implementation in Ruby (Condorcet voting method)'
end
